namespace Advocu.WebApp;

public class AdvocuDataService
{
    public List<string> GetTags()
    {
        return new List<string>
        {
            "AI",
            "AI - AI Studio",
            "AI - Agent Development Kit (ADK)",
            "AI - Agents",
            "AI - Colab",
            "AI - Gemini",
            "AI - Gemma",
            "AI - Generative AI",
            "AI - JAX",
            "AI - Kaggle",
            "AI - Keras",
            "AI - LLM",
            "AI - LiteRT",
            "AI - ML Engineering (MLOps)",
            "AI - MediaPipe",
            "AI - On-Device AI",
            "AI - Responsible AI",
            "AI - TPU",
            "AI - TensorFlow",
            "AI - Vertex AI",
            "AI Math Clubs",
            "AI Paper Reading Clubs",
            "AR/VR",
            "Android",
            "Android - ARCore",
            "Android - Android Auto",
            "Android - Android Dev Tools",
            "Android - Android Studio",
            "Android - Android TV",
            "Android - App Architecture & Arch Components",
            "Android - App Indexing",
            "Android - App Performance",
            "Android - App Quality",
            "Android - Camera",
            "Android - Composer",
            "Android - Form Factors",
            "Android - Gemini Nano",
            "Android - Jetpack",
            "Android - Jetpack Compose",
            "Android - Kotlin",
            "Android - Material Design",
            "Android - Media",
            "Android - Modern Android Development",
            "Android - Modern UI",
            "Android - NDK",
            "Android - Passkeys",
            "Android - Performance",
            "Android - Vulkan",
            "Android - Wear OS",
            "Android - Widgets",
            "Android - XR",
            "Angular",
            "Build with AI",
            "Cloud - AI Tools",
            "Cloud - API Gateways",
            "Cloud - App Development",
            "Cloud - Compute, Networking, Storage",
            "Cloud - Data",
            "Cloud - Operations & Management",
            "Cloud - Security",
            "Cloud - Serverless & Containers",
            "Cloud Study Jam",
            "Dart",
            "DevFest",
            "Diversity & Inclusion",
            "Earth Engine",
            "Firebase",
            "Firebase - A/B Testing",
            "Firebase - AI Logic",
            "Firebase - AI Monitoring",
            "Firebase - Analytics",
            "Firebase - App Hosting",
            "Firebase - Authentication",
            "Firebase - Cloud Messaging",
            "Firebase - Data Connect",
            "Firebase - Firebase Studio",
            "Firebase - Firestore",
            "Firebase - Genkit",
            "Firebase - Performance",
            "Firebase - Realtime Database",
            "Firebase - Remote Config",
            "Firebase - Test Lab",
            "Flutter",
            "Golang",
            "Google Cloud",
            "Google I/O Extended",
            "Google Maps Platform",
            "Google Workspace",
            "Identity",
            "Identity - Google OAuth",
            "Identity - Sign in with Google",
            "International Women's Day",
            "ML Study Jams",
            "Open Source",
            "Payments",
            "Payments - Google Pay",
            "Payments - Google Wallet",
            "Road to Google Developers Certification",
            "UX / UI Design",
            "Web",
            "Web - AI for Web Developers",
            "Web - Browser Extensions",
            "Web - CSS & UI",
            "Web - DevTools & Browser Automation",
            "Web - Fugu/PWA APIs",
            "Web - Identity",
            "Web - Performance",
            "Workspace - Add Ons",
            "Workspace - AppSheet",
            "Workspace - Google Apps Script",
            "Workspace - Google Workspace (REST) APIs"
        };
    }
}
